### ISSUE TITLE
Better i18n sidebar support

### ISSUE THREAD

**Issue by Lorde627** [HiDeoo/starlight-sidebar-topics#7]
### Is your feature request related to a problem?

I'm always frustrated when trying to create multilingual documentation with starlight-sidebar-topics, as it only supports i18n for top-level labels but not nested items. This creates an inconsistent user experience where only parent menu items can be translated while child items remain in a single language.

### Describe the solution you'd like

Enable i18n object support for the `label`, `link`, etc field at all nesting levels in the sidebar configuration. For example:

```
plugins: [
  starlightSidebarTopics([
    {
      label: {
        en: 'Manual',
        'zh-CN': '文档',
      },
      items: [
        {
          label: {
            en: 'accessibility',
            'zh-CN': '辅助功能',
          },
          collapsed: true,
          autogenerate: { directory: 'manual/Accessibility Features' }
        }
      ]
    }
  ])
]
```

### Describe alternatives you've considered

1. Using separate sidebar configurations for each language, but this would lead to maintenance overhead and potential inconsistencies
2. Creating a custom translation layer outside the plugin, but this would add unnecessary complexity
3. Using language-specific directory structures, but this would make the codebase more difficult to maintain

### Additional Context

This enhancement would align with Astro/Starlight's strong internationalization capabilities and provide a more cohesive documentation experience for multilingual projects. It would particularly benefit projects that:

1. Maintain documentation in multiple languages
2. Need consistent navigation experience across languages
3. Want to avoid duplicate sidebar configurations

**Comment by HiDeoo** [comment]
Thanks for your report.

> it only supports i18n for top-level labels but not nested items.

I'm not sure what you mean by "nested items" or "top-level labels".

> This enhancement would align with Astro/Starlight's strong internationalization capabilities and provide a more cohesive documentation experience for multilingual projects.

As [documented](https://starlight-sidebar-topics.netlify.app/docs/configuration/#items), the `items` property accepts the same configuration as the [Starlight `sidebar` configuration](https://starlight.astro.build/reference/configuration/#sidebar). This also means that everything documented in the [Starlight Sidebar Navigation Internationalization guide](https://starlight.astro.build/guides/sidebar/#internationalization) applies to the `items` property as well.

For example, using the example you provided and following the previous link, the following configuration would work:

```js
plugins: [
  starlightSidebarTopics([
    {
      label: {
        en: 'Manual',
        'zh-CN': '文档',
      },
      items: [
        {
          label: 'accessibility',
          translations: {
            'zh-CN': '辅助功能',
          },
          collapsed: true,
          autogenerate: { directory: 'manual/Accessibility Features' }
        }
      ]
    }
  ])
]
```

For the auto-generated items, they will automatically use translated page titles from content frontmatter by default.

**Comment by Lorde627** [comment]
Thanks, this is incredibly helpful!

By the way, I’ve been trying to integrate [unplugin-icons](https://hideoo.dev/notes/starlight-third-party-icon-sets#install-unplugin-icons) into my project. However, it seems that changing the topic icon to an Iconify icon isn’t supported. Do you happen to have any insights on how to make this work?

**Comment by HiDeoo** [comment]
Thanks for the follow-up.

> By the way, I’ve been trying to integrate [unplugin-icons](https://hideoo.dev/notes/starlight-third-party-icon-sets#install-unplugin-icons) into my project. However, it seems that changing the topic icon to an Iconify icon isn’t supported. Do you happen to have any insights on how to make this work?

This is a topic I commented on in [this post](https://github.com/HiDeoo/starlight-sidebar-topics/issues/5#issuecomment-2485029609):

> There are currently discussions and plans to add support for more icons into Starlight with support for most 3rd party icons through something like [Iconify](https://iconify.design/). I think I'd like to see where and how that goes before potentially manually adding support for custom icons. If it allows for a unified way to add icons from multiple sources, even custom ones, through a single API, I think that would be the best way to go.
